### ISSUE TITLE
[questions]  Too general to even come up with a title

### ISSUE THREAD

**Issue by faddat** [sneak/docker-steemd#1]
what's steemd.run, exactly and how do you intend it to be used?

If I add these lines to steemd.run, will steem pick up the changes in the config from the env vars?

ENABLE_PLUGIN = witness account_history tags follow market_history
PUBLIC_API = database_api login_api network_broadcast_api follow_api market_history_api

I think steemd.run is a kind of script that is started when the docker container is and that stuf fin its environment should get noticed.  But-- I'm certain I'm not certain ;).  

Also, I hope you don't care (I'll be giving attribution, because hells yeah to this Dockerfile and three cheers to you) I'm going to submit a pull request with this in a subfolder called docker to the main repo, steemit/steem.  If you do care, e-mail me, and I won't.  

GREAT WORK!

Oh, yeah-- nice touch with taking the care to ensure the user can select the closest ubuntu repos to them.  10/10, I think.....

**Comment by sneak** [comment]
I will handle submitting this upstream soon - leave it to me.  I intend to integrate significant testing in the build process, as well.

**Comment by sneak** [comment]
steemd.run is the script that is run by supervise/runit/daemontools in `/etc/service/steemd/run` (restarted on exit).  It receives the environment variables from the docker container, so if you put those vars in it, it will work.  Make sure you specify sensible defaults for the variables (examples in steemd.run) or leave it out of `$ARGS` entirely if not specified by the user, as the p2p node should always come up working even with no args passed in (e.g. `docker run -d sneak/steemd`).

**Comment by faddat** [comment]
Gotcha.  I *think* I know what you're referring to bow and well the honest
fact of the matter is that I may have submitted this upstream (not certain)
what I am certain of however is that my upstream submission sucked.

**Comment by sneak** [comment]
Please don't redistribute my code; you have no license to it and you expose any projects to which you submit it to to legal liability.
